Repository SwitchbladeBot/bladey-web, pull requests merged in 2018-07, with the labels that each got.

#2 Homepage improvements
  package-lock.json
  package.json
  src/App.vue
  src/assets/main.scss
  src/components/Homepage.vue
  src/components/LoginCallback.vue
  src/components/Navbar.vue
  src/main.js
  src/router/index.js
Labels: Do not merge, Enhancement, Feature, WIP

#5 Homepage improvements and oauth implementation
  config/dev.env.js
  config/prod.env.js
  package-lock.json
  package.json
  src/App.vue
  src/assets/main.scss
  src/components/Homepage.vue
  src/components/LoginAuth.vue
  src/components/LoginCallback.vue
  src/components/Navbar.vue
  src/main.js
  src/oauth/Discord.js
  src/oauth/Guild.js
  src/oauth/User.js
  src/router/index.js
Labels: Enhancement, Feature, Ready for Review

#13 Lottastuff
  config/dev.env.js
  config/prod.env.js
  package-lock.json
  src/assets/main.scss
  src/components/Footer.vue
  src/components/Navbar.vue
  src/pages/Contributors.vue
  src/pages/Dashboard.vue
  src/router/index.js
Labels: Enhancement, Feature

#14 Material Design Icons and Contributors Tweaks
  package-lock.json
  package.json
  src/assets/main.scss
  src/components/Navbar.vue
  src/main.js
  src/oauth/User.js
  src/oauth/VueDiscordOAuth.js
  src/pages/Contributors.vue
  src/pages/Homepage.vue
  src/pages/NotFound.vue
  src/pages/ServerSelector.vue
Labels: Enhancement, Feature

#17 Contributors Status
  src/pages/Contributors.vue
  static/img/status-dnd.png
  static/img/status-idle.png
  static/img/status-offline.png
  static/img/status-online.png
Labels: Enhancement, Feature, Ready for Review
