Repository SwitchbladeBot/bladey-web, pull requests merged in 2019-02, with the labels that each got.

#36 OAuth rework
  build/vue-loader.conf.js
  build/webpack.base.conf.js
  build/webpack.dev.conf.js
  build/webpack.prod.conf.js
  config/dev.env.js
  config/prod.env.js
  index.html
  package-lock.json
  package.json
  src/App.vue
  src/api/VueSwitchbladeApi.js
  src/assets/main.scss
  src/components/ChannelList.vue
  src/components/Navbar.vue
  src/oauth/VueDiscordOAuth.js
  src/pages/Contributors.vue
  src/pages/Dashboard.vue
  src/pages/Homepage.vue
  src/pages/LoginAuth.vue
  src/pages/NotFound.vue
  src/pages/ServerSelector.vue
  src/router/index.js
Labels: Code quality, Enhancement, Feature, High priority, Refactor

#43 Removing things
  src/components/Navbar.vue
Labels: PR: unreviewed

#41 Guild dashboard
  src/App.vue
  src/api/Guild.js
  src/api/VueSwitchbladeApi.js
  src/assets/main.scss
  src/components/dashboard/DashboardGeneral.vue
  src/components/dashboard/DashboardModeration.vue
  src/components/profile/ProfileConnections.vue
  src/components/profile/ProfileSocial.vue
  src/pages/Dashboard.vue
  src/pages/Profile.vue
  src/router/index.js
Labels: Enhancement, Feature, PR: reviewed-approved, PR: unreviewed, Ready for Review
